### ISSUE TITLE
[BUG]: Difficulty in building project that build with cibuildhweel

### ISSUE THREAD

**Issue by laggykiller** [wjakob/nanobind#262] opened 2023-08-14 11:32 UTC
### Problem description

In GitHub runner, cibuildwheel setups python 3.7, which is not supported by nanobind (Attempting to install nanobind would cause `TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'`)
The cause is https://github.com/wjakob/nanobind/blob/master/setup.py#L49 due to `dirs_exist_ok` option not existing before python 3.8 (https://docs.python.org/3/library/shutil.html#shutil.copytree)

See: https://github.com/laggykiller/apngasm-python/actions/runs/5854803439/job/15871376469

However, if I install it in the venv setup by cibuildwheel, then:
```
CMake Error at cmake/QueryPythonForNanobind.cmake:37 (find_package):
    Could not find a package configuration file provided by "nanobind" with any
    of the following names:
  
      nanobindConfig.cmake
      nanobind-config.cmake
  
    Add the installation prefix of "nanobind" to CMAKE_PREFIX_PATH or set
    "nanobind_DIR" to a directory containing one of the above files.  If
    "nanobind" provides a separate development package or SDK, be sure it has
    been installed.
```
See: https://github.com/laggykiller/apngasm-python/actions/runs/5855058420/job/15872111888

Of course I can just `add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/ext/nanobind)`, but I think we should also make the pip method possible.

**Comment by wjakob** [comment] 2023-08-14 12:10
See also the nanobind_example project.

**Comment by laggykiller** [comment] 2023-08-14 12:24
I thought of another method, which is to check for existance of `<venv>/Lib/site-packages/nanobind/cmake` (Windows) or `<venv>/lib/site-packages/pythonX.Y/nanobind/cmake` (Other), and set `nanobind_ROOT` to the directory if it exist.

Reference: https://docs.python.org/3/library/venv.html#creating-virtual-environments

However, I don't think there is easy way to find `pythonX.Y` that is being used for building

**Comment by wjakob** [comment] 2023-08-14 12:25
I don't understand. The example project also uses cibuildwheel, and everything works just fine. What is different in your use case?

**Comment by tttapa** [comment] 2023-08-14 12:26
The clue is in the lines above the error you posted:

```
  -- Found Python: C:/hostedtoolcache/windows/Python/3.11.4/x64/python3.exe (found suitable version "3.11.4", minimum required is "3.8") found components: Interpreter Development.Module 
  -- Detecting nanobind CMake location
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'nanobind'
  CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:855 (_find_package):
    Could not find a package configuration file provided by "nanobind" with any
    of the following names:
  
      nanobindConfig.cmake
      nanobind-config.cmake
  
    Add the installation prefix of "nanobind" to CMAKE_PREFIX_PATH or set
    "nanobind_DIR" to a directory containing one of the above files.  If
    "nanobind" provides a separate development package or SDK, be sure it has
    been installed.
```
The Python installation that was found is the default GitHub actions one, not the one from cibuildwheel. This global Python installation does not have nanobind installed, so locating it fails.

The reason that the wrong version of Python is found is that you're using `find_package(Python ...)` in your CMake scripts, but you did not set `find_python = true` in your py-build-cmake config.  
See https://github.com/tttapa/py-build-cmake/blob/9631696c2dec7b31551f67c5df9943ff0f0a19d5/examples/nanobind-project/pyproject.toml#L45-L46

**Comment by tttapa** [comment] 2023-08-14 13:55
@laggykiller feel free to open an issue in [tttapa/py-build-cmake](https://github.com/tttapa/py-build-cmake), let's continue the discussion over there.

To make things easier to debug, please enable verbose output, add the following to `pyproject.toml`:

```toml
[tool.cibuildwheel]
build-verbosity = 1
environment = { PY_BUILD_CMAKE_VERBOSE="1" }
```
And set `build_args = ["-j", "--verbose"]` in `[tool.py-build-cmake.cmake]`.

**Comment by wjakob** [comment] 2023-08-14 14:28
I will close the issue here, seems like it's not related to nanobind.

**Closed by wjakob** 2023-08-14 14:28 UTC

**Comment by wjakob** [comment] 2023-08-14 14:29
I have one stupid question for @tttapa : what's the difference between `py-build-cmake` and `scikit-build` or the newer `scikit-build-core`. I was only familiar with the latter two. The description of `py-build-cmake` sounds to me like it's intended for similar goals.

**Comment by tttapa** [comment] 2023-08-14 16:40
@wjakob I started developing py-build-cmake before scikit-build-core existed, it was born out of a necessity to reliably cross-compile some of my packages (this was very painful to do in setuptools-based backends such as the original scikit-build).  
Strong cross-compilation support is still one of the main goals today, as well as support for editable installs, creating separate wheels with secondary artifacts (like debugging symbols), a direct command-line interface, etc., but there's indeed quite a bit of overlap with scikit-build-core.

**Comment by wjakob** [comment] 2023-08-14 18:51
Thanks for the clarification!

**Comment by tttapa** [comment] 2023-08-15 11:47
Since it seems to be a general CMake mistake unrelated to py-build-cmake: the linker error was caused by calling `find_package(Python ...)` before `project(...)`. Moving the `find_package` call below the `project` call resolves it.
